on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - shell: pwsh
      env:
        TAG_NAME: ${{ github.event.release.tag_name }}}
      run: |
        Write-Output $env:TAG_NAME